// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod cpss {

#[allow(unused_imports, dead_code)]
pub mod tom {

#[allow(unused_imports, dead_code)]
pub mod sensord {


pub enum SensorFrameOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SensorFrame<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SensorFrame<'a> {
  type Inner = SensorFrame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SensorFrame<'a> {
  pub const VT_GYRO_X: ::flatbuffers::VOffsetT = 4;
  pub const VT_GYRO_Y: ::flatbuffers::VOffsetT = 6;
  pub const VT_GYRO_Z: ::flatbuffers::VOffsetT = 8;
  pub const VT_ACCEL_X: ::flatbuffers::VOffsetT = 10;
  pub const VT_ACCEL_Y: ::flatbuffers::VOffsetT = 12;
  pub const VT_ACCEL_Z: ::flatbuffers::VOffsetT = 14;
  pub const VT_TEMPERATURE: ::flatbuffers::VOffsetT = 16;
  pub const VT_PRESSURE: ::flatbuffers::VOffsetT = 18;
  pub const VT_ALTITUDE: ::flatbuffers::VOffsetT = 20;
  pub const VT_SPEED: ::flatbuffers::VOffsetT = 22;
  pub const VT_HEADING: ::flatbuffers::VOffsetT = 24;
  pub const VT_LATITUDE: ::flatbuffers::VOffsetT = 26;
  pub const VT_LONGITUDE: ::flatbuffers::VOffsetT = 28;
  pub const VT_ESTIMATED_SPEED_ERROR: ::flatbuffers::VOffsetT = 30;
  pub const VT_ESTIMATED_LATITUDE_ERROR: ::flatbuffers::VOffsetT = 32;
  pub const VT_ESTIMATED_LONGITUDE_ERROR: ::flatbuffers::VOffsetT = 34;
  pub const VT_SATELLITES: ::flatbuffers::VOffsetT = 36;
  pub const VT_VALID_SATELLITES: ::flatbuffers::VOffsetT = 38;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SensorFrame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SensorFrameArgs
  ) -> ::flatbuffers::WIPOffset<SensorFrame<'bldr>> {
    let mut builder = SensorFrameBuilder::new(_fbb);
    builder.add_longitude(args.longitude);
    builder.add_latitude(args.latitude);
    builder.add_estimated_longitude_error(args.estimated_longitude_error);
    builder.add_estimated_latitude_error(args.estimated_latitude_error);
    builder.add_estimated_speed_error(args.estimated_speed_error);
    builder.add_heading(args.heading);
    builder.add_speed(args.speed);
    builder.add_altitude(args.altitude);
    builder.add_pressure(args.pressure);
    builder.add_temperature(args.temperature);
    builder.add_accel_z(args.accel_z);
    builder.add_accel_y(args.accel_y);
    builder.add_accel_x(args.accel_x);
    builder.add_gyro_z(args.gyro_z);
    builder.add_gyro_y(args.gyro_y);
    builder.add_gyro_x(args.gyro_x);
    builder.add_valid_satellites(args.valid_satellites);
    builder.add_satellites(args.satellites);
    builder.finish()
  }


  #[inline]
  pub fn gyro_x(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_GYRO_X, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn gyro_y(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_GYRO_Y, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn gyro_z(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_GYRO_Z, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn accel_x(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ACCEL_X, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn accel_y(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ACCEL_Y, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn accel_z(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ACCEL_Z, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn temperature(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_TEMPERATURE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn pressure(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_PRESSURE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn altitude(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ALTITUDE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn speed(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_SPEED, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn heading(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_HEADING, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn latitude(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SensorFrame::VT_LATITUDE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn longitude(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SensorFrame::VT_LONGITUDE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn estimated_speed_error(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ESTIMATED_SPEED_ERROR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn estimated_latitude_error(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ESTIMATED_LATITUDE_ERROR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn estimated_longitude_error(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SensorFrame::VT_ESTIMATED_LONGITUDE_ERROR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn satellites(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SensorFrame::VT_SATELLITES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn valid_satellites(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SensorFrame::VT_VALID_SATELLITES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SensorFrame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f32>("gyro_x", Self::VT_GYRO_X, false)?
     .visit_field::<f32>("gyro_y", Self::VT_GYRO_Y, false)?
     .visit_field::<f32>("gyro_z", Self::VT_GYRO_Z, false)?
     .visit_field::<f32>("accel_x", Self::VT_ACCEL_X, false)?
     .visit_field::<f32>("accel_y", Self::VT_ACCEL_Y, false)?
     .visit_field::<f32>("accel_z", Self::VT_ACCEL_Z, false)?
     .visit_field::<f32>("temperature", Self::VT_TEMPERATURE, false)?
     .visit_field::<f32>("pressure", Self::VT_PRESSURE, false)?
     .visit_field::<f32>("altitude", Self::VT_ALTITUDE, false)?
     .visit_field::<f32>("speed", Self::VT_SPEED, false)?
     .visit_field::<f32>("heading", Self::VT_HEADING, false)?
     .visit_field::<f64>("latitude", Self::VT_LATITUDE, false)?
     .visit_field::<f64>("longitude", Self::VT_LONGITUDE, false)?
     .visit_field::<f32>("estimated_speed_error", Self::VT_ESTIMATED_SPEED_ERROR, false)?
     .visit_field::<f32>("estimated_latitude_error", Self::VT_ESTIMATED_LATITUDE_ERROR, false)?
     .visit_field::<f32>("estimated_longitude_error", Self::VT_ESTIMATED_LONGITUDE_ERROR, false)?
     .visit_field::<u8>("satellites", Self::VT_SATELLITES, false)?
     .visit_field::<u8>("valid_satellites", Self::VT_VALID_SATELLITES, false)?
     .finish();
    Ok(())
  }
}
pub struct SensorFrameArgs {
    pub gyro_x: f32,
    pub gyro_y: f32,
    pub gyro_z: f32,
    pub accel_x: f32,
    pub accel_y: f32,
    pub accel_z: f32,
    pub temperature: f32,
    pub pressure: f32,
    pub altitude: f32,
    pub speed: f32,
    pub heading: f32,
    pub latitude: f64,
    pub longitude: f64,
    pub estimated_speed_error: f32,
    pub estimated_latitude_error: f32,
    pub estimated_longitude_error: f32,
    pub satellites: u8,
    pub valid_satellites: u8,
}
impl<'a> Default for SensorFrameArgs {
  #[inline]
  fn default() -> Self {
    SensorFrameArgs {
      gyro_x: 0.0,
      gyro_y: 0.0,
      gyro_z: 0.0,
      accel_x: 0.0,
      accel_y: 0.0,
      accel_z: 0.0,
      temperature: 0.0,
      pressure: 0.0,
      altitude: 0.0,
      speed: 0.0,
      heading: 0.0,
      latitude: 0.0,
      longitude: 0.0,
      estimated_speed_error: 0.0,
      estimated_latitude_error: 0.0,
      estimated_longitude_error: 0.0,
      satellites: 0,
      valid_satellites: 0,
    }
  }
}

pub struct SensorFrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SensorFrameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_gyro_x(&mut self, gyro_x: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_GYRO_X, gyro_x, 0.0);
  }
  #[inline]
  pub fn add_gyro_y(&mut self, gyro_y: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_GYRO_Y, gyro_y, 0.0);
  }
  #[inline]
  pub fn add_gyro_z(&mut self, gyro_z: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_GYRO_Z, gyro_z, 0.0);
  }
  #[inline]
  pub fn add_accel_x(&mut self, accel_x: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ACCEL_X, accel_x, 0.0);
  }
  #[inline]
  pub fn add_accel_y(&mut self, accel_y: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ACCEL_Y, accel_y, 0.0);
  }
  #[inline]
  pub fn add_accel_z(&mut self, accel_z: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ACCEL_Z, accel_z, 0.0);
  }
  #[inline]
  pub fn add_temperature(&mut self, temperature: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_TEMPERATURE, temperature, 0.0);
  }
  #[inline]
  pub fn add_pressure(&mut self, pressure: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_PRESSURE, pressure, 0.0);
  }
  #[inline]
  pub fn add_altitude(&mut self, altitude: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ALTITUDE, altitude, 0.0);
  }
  #[inline]
  pub fn add_speed(&mut self, speed: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_SPEED, speed, 0.0);
  }
  #[inline]
  pub fn add_heading(&mut self, heading: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_HEADING, heading, 0.0);
  }
  #[inline]
  pub fn add_latitude(&mut self, latitude: f64) {
    self.fbb_.push_slot::<f64>(SensorFrame::VT_LATITUDE, latitude, 0.0);
  }
  #[inline]
  pub fn add_longitude(&mut self, longitude: f64) {
    self.fbb_.push_slot::<f64>(SensorFrame::VT_LONGITUDE, longitude, 0.0);
  }
  #[inline]
  pub fn add_estimated_speed_error(&mut self, estimated_speed_error: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ESTIMATED_SPEED_ERROR, estimated_speed_error, 0.0);
  }
  #[inline]
  pub fn add_estimated_latitude_error(&mut self, estimated_latitude_error: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ESTIMATED_LATITUDE_ERROR, estimated_latitude_error, 0.0);
  }
  #[inline]
  pub fn add_estimated_longitude_error(&mut self, estimated_longitude_error: f32) {
    self.fbb_.push_slot::<f32>(SensorFrame::VT_ESTIMATED_LONGITUDE_ERROR, estimated_longitude_error, 0.0);
  }
  #[inline]
  pub fn add_satellites(&mut self, satellites: u8) {
    self.fbb_.push_slot::<u8>(SensorFrame::VT_SATELLITES, satellites, 0);
  }
  #[inline]
  pub fn add_valid_satellites(&mut self, valid_satellites: u8) {
    self.fbb_.push_slot::<u8>(SensorFrame::VT_VALID_SATELLITES, valid_satellites, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SensorFrameBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SensorFrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SensorFrame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SensorFrame<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SensorFrame");
      ds.field("gyro_x", &self.gyro_x());
      ds.field("gyro_y", &self.gyro_y());
      ds.field("gyro_z", &self.gyro_z());
      ds.field("accel_x", &self.accel_x());
      ds.field("accel_y", &self.accel_y());
      ds.field("accel_z", &self.accel_z());
      ds.field("temperature", &self.temperature());
      ds.field("pressure", &self.pressure());
      ds.field("altitude", &self.altitude());
      ds.field("speed", &self.speed());
      ds.field("heading", &self.heading());
      ds.field("latitude", &self.latitude());
      ds.field("longitude", &self.longitude());
      ds.field("estimated_speed_error", &self.estimated_speed_error());
      ds.field("estimated_latitude_error", &self.estimated_latitude_error());
      ds.field("estimated_longitude_error", &self.estimated_longitude_error());
      ds.field("satellites", &self.satellites());
      ds.field("valid_satellites", &self.valid_satellites());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `SensorFrame`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sensor_frame_unchecked`.
pub fn root_as_sensor_frame(buf: &[u8]) -> Result<SensorFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<SensorFrame>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `SensorFrame` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_sensor_frame_unchecked`.
pub fn size_prefixed_root_as_sensor_frame(buf: &[u8]) -> Result<SensorFrame<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<SensorFrame>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `SensorFrame` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sensor_frame_unchecked`.
pub fn root_as_sensor_frame_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SensorFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<SensorFrame<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `SensorFrame` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_sensor_frame_unchecked`.
pub fn size_prefixed_root_as_sensor_frame_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SensorFrame<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<SensorFrame<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a SensorFrame and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `SensorFrame`.
pub unsafe fn root_as_sensor_frame_unchecked(buf: &[u8]) -> SensorFrame<'_> {
  unsafe { ::flatbuffers::root_unchecked::<SensorFrame>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed SensorFrame and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `SensorFrame`.
pub unsafe fn size_prefixed_root_as_sensor_frame_unchecked(buf: &[u8]) -> SensorFrame<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<SensorFrame>(buf) }
}
#[inline]
pub fn finish_sensor_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<SensorFrame<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_sensor_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<SensorFrame<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod sensord
}  // pub mod tom
}  // pub mod cpss

